version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/storage/dsadapter/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/storage/benchmarks/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/storage/bsadapter/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/storage/bsrvadapter/"
    schedule:
      interval: "weekly"
