version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/storage/dsadapter/"
      - "/storage/benchmarks/"
      - "/storage/bsadapter/"
      - "/storage/bsrvadapter/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5
    groups:
      shared-dependencies:
        group-by: "dependency-name"
